name: hrtsimul
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.4
  flutter_libserialport: ^0.4.0
  #libserialport: 
  #  path: libserialport-0.3.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  expressions: ^0.2.5+2
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/trans_nivel.png
    - assets/bomba.png    
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf   